version: '3.8'

services:

  traefik:
    image: traefik:latest
    command: --api.insecure=true --providers.docker
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`www.traefik.lan`)
      - traefik.http.services.traefik.loadbalancer.server.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    labels:
      - traefik.enable=false
    depends_on:
      - traefik
    volumes:
      - ./data/mysql:/var/lib/mysql:rw,delegated

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: ${MYSQL_PORT}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin.rule=Host(`www.phpmyadmin.lan`)
    links:
      - mysql
    depends_on:
      - traefik
      - mysql

  symfony:
    image: aurelienandre/symfony-lts:latest
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.symfony.rule=Host(`www.symfony.lan`)
      - traefik.http.services.symfony.loadbalancer.server.port=80
    links:
      - mysql
    depends_on:
      - traefik
      - mysql
    volumes:
      - ./src:/var/www/html:rw,delegated
