#!/bin/bash

if [ "$1" = 'supervisord' ]; then

  if [ ! -s "/etc/php/8.0/90-php.ini" ]; then

    for e in "${!PHP_@}"; do

      VARIABLE=$(echo "$e" | sed -e 's/PHP_/''/g' | sed -e 's/__/'.'/g' | awk '{print tolower($0)}')

      VALUE=$(printf '${%s}' "$e")

      echo "$VARIABLE=$VALUE" >> "/etc/php/8.0/90-php.ini"

    done

  fi

  while [ ! -f "/var/www/html/vendor/autoload.php" ]; do

    (echo >&2 "Waiting for Composer to be ready...")

    sleep 2

  done

  if [ -n "$(ls -A /var/www/html/migrations/*.php 2>/dev/null)" ]; then

    until bin/console doctrine:query:sql "select 1" >/dev/null 2>&1; do

      (echo >&2 "Waiting for MySQL to be ready...")

      sleep 1

    done

    bin/console \
      doctrine:migrations:migrate \
      --no-interaction
  fi

  if [ -n "$(ls -A /var/www/html/public/bundles/ 2>/dev/null)" ]; then

    bin/console \
      assets:install \
      --no-interaction

  fi

fi

if [ "$1" = 'supervisorctl' ]; then

  while [ ! -f "/var/pid/supervisord.pid" ]; do

    (echo >&2 "Waiting for Supervisor to be ready...")

    sleep 2

  done

fi

if [ "$1" = 'nginx' ]; then

  while [ ! -f "/var/pid/php8.0-fpm.pid" ]; do

    (echo >&2 "Waiting for Fpm to be ready...")

    sleep 2

  done

fi

exec "$@"
